directories:
  output: release
  buildResources: build
appId: com.hyperverse.game
productName: Hyperverse
files:
  - filter:
      - dist/**/*
      - dist-electron/**/*
mac:
  target: dmg
  icon: build/icon.icns
  category: public.app-category.games
win:
  target: nsis
  icon: build/icon.ico
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
electronVersion: 34.5.8
